# This is used for the AWS ECS deployment.
version: "3"
services:
  hsl_bike_app:
    # Pulls the image from docker hub, does not use the local build image.
    image: joshuahsudo/hsl_bike_app:latest
    working_dir: /home/node/app
    ports:
      - "8080:8080"
    secrets:
      - app_environment
    depends_on:
      - app_database
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16Gb

  app_database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    ports:
      - "27017:27017"
    secrets:
      - db_root_username
      - db_root_password
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16Gb
secrets:
  db_root_username:
    file: ../credentials/.db_root_username.env
  db_root_password:
    file: ../credentials/.db_root_password.env
  app_environment:
    file: ../app.env
volumes:
  mongo-data: