# This will replicate a isolated production enviroment not build from source.
version: "3"
services:
  hsl_bike_app:
    # Pulls the image from docker hub, does not use the local build image
    # This will ensure the same docker image is used everywhere.
    image: joshuahsudo/hsl_bike_app:latest
    working_dir: /home/node/app
    ports:
      - "8080:8080"
    secrets:
      - app_environment
    depends_on:
      - app_database
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16Gb

  app_database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    secrets:
      - database_environment
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16Gb
secrets:
  database_environment:
    file: ../database.env
  app_environment:
    file: ../app.env
volumes:
  mongo-data: