# This will replicate a isolated production enviroment not build from source.
version: "3"
services:
  hsl_bike_app:
    # pulls the image from docker hub, does not use the local build image
    image: joshuahsudo/hsl_bike_app:latest
    working_dir: /home/node/app
    ports:
      - "8080:8080"
    expose:
      - "8081"
    env_file: "../.env"
    command: yarn prod
    depends_on:
      - app_database
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16Gb

  app_database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file: "../.env"
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16Gb
volumes:
  mongo-data: