version: "3"
services:
  hsl_bike_app:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.yml
    working_dir: /home/node/app
    env_file: 
      - ../.env
    depends_on:
      - app_database

  app_database:
    image: mongo
    restart: always
    env_file: 
      - ../database.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
