#This compose file is for producing the production image
version: "3"
services:
  hsl_bike_app:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.prod.yml
    working_dir: /home/node/app
    ports:
      - "8080:8080"
    secrets:
      - app_environment
    depends_on:
      - app_database

  app_database:
    image: mongo
    restart: always
    env_file: 
      - ../database.env
    # command: bash -c source /run/secrets/dabatase_environment
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

secrets:
  database_environment:
    file: ../database.env
  app_environment:
    file: ../app.env
volumes:
  mongo-data:
