#This compose file is for producing the production image
version: "3"
services:
  hsl_bike_app:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.prod.yml
    working_dir: /home/node/app
    environment:
      - MONGO_URI_FILE=/run/secrets/db_mongo_uri
    ports:
      - "8080:8080"
    secrets:
      - app_environment
      - db_mongo_uri
    depends_on:
      - app_database

  app_database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    ports:
      - "27017:27017"
    secrets:
      - db_root_username
      - db_root_password
    volumes:
      - mongo-data:/data/db

secrets:
  db_root_username:
    file: ../credentials/.db_root_username.env
  db_root_password:
    file: ../credentials/.db_root_password.env
  app_environment:
    file: ../app.env
  db_mongo_uri:
    file: ../credentials/.db_mongo_uri.env
volumes:
  mongo-data:
