# This will replicate a isolated production enviroment.
version: "3"
services:
  hsl_bike_app:
    # pulls the image from docker hub, does not use the local build image
    image: hsl_bike_app:latest
    working_dir: /home/node/app
    ports:
      - "8080:8080"
    expose:
      - "8081"
    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGO_URI=mongodb://app_database:27017/dev-academy
    command: yarn prod
    depends_on:
      - app_database

  app_database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
