#This compose file is for producing the production image
version: "3.8"
services:
  hsl_bike_app:
    container_name: hsl_bike_app
    build:
      context: ../
      dockerfile: ./docker/dockerfile.prod.yml
    working_dir: /home/node/app
    # Set the MONGO URI to a file so that it can be read from the secrets manager.
    environment:
      PORT: 8080
      NODE_ENV: production
      MONGO_URI_FILE: /run/secrets/db_mongo_uri
    ports:
      - "8080:8080"
    secrets:
      - db_mongo_uri
      
secrets:
  db_mongo_uri:
    file: ../environment/db_mongo_uri.env
volumes:
  mongo-data:
