# This is used for the AWS ECS deployment.
version: "3"
services:
  hsl_bike_app:
    # Pulls the image from docker hub, does not use the local build image.
    image: joshuahsudo/hsl_bike_app:latest
    working_dir: /home/node/app
    environment:
      PORT: 8080
      NODE_ENV: production
      MONGO_URI: mongodb://placeholder:placeholder@app_database:27017/hsl_bike_app
    ports:
      - "8080:8080"
    depends_on:
      - app_database
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16Gb

  app_database:
    image: mongo
    restart: always
    environment:
      # This will be overriden in the github actions.
      MONGO_INITDB_ROOT_USERNAME: placeholder
      MONGO_INITDB_ROOT_PASSWORD: placeholder
      MONGO_INITDB_DATABASE: hsl_bike_app
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16Gb
volumes:
  mongo-data: