FROM node:gallium-bullseye-slim
WORKDIR /home/node/app

# Copy all files from the root directory
COPY . .
RUN yarn install --production
# Need this to decompress the dataset tar files
RUN apt-get update
RUN apt-get install bzip2

EXPOSE 3000

CMD ["yarn", "start"]