# This is used for the AWS ECS deployment.
version: "3"
services:
  hsl_bike_app:
    # Pulls the image from docker hub, does not use the local build image.
    image: joshuahsudo/hsl_bike_app:latest
    working_dir: /home/node/app
    ports:
      - "8080:8080"
    secrets:
      - app_environment
    depends_on:
      - app_database
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16Gb

  app_database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    ports:
      - "27017:27017"
    secrets:
      - db_root_username
      - db_root_password
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16Gb
secrets:
  db_root_username:
    name: "arn:aws:secretsmanager:ap-southeast-2:788286108805:secret:hsl-bike-app-db-username-pVYYRG"
    external: true
  db_root_password:
    name: "arn:aws:secretsmanager:ap-southeast-2:788286108805:secret:hsl-bike-app-db-password-RtF4cE"
    external: true
  app_environment:
    name: "arn:aws:secretsmanager:ap-southeast-2:788286108805:secret:hsl-bike-app-mongo-uri-4h0gb5"
    external: true
volumes:
  mongo-data: