# This is used for the AWS ECS deployment.
version: "3.8"
services:
  hsl_bike_app:
    container_name: hsl_bike_app
    # Pulls the image from docker hub, does not use the local build image.
    image: joshuahsudo/hsl_bike_app:latest
    working_dir: /home/node/app
    environment:
      PORT: 8080
      NODE_ENV: production
      MONGO_URI_FILE: /run/secrets/db_mongo_uri
    ports:
      - "8080:8080"
    secrets:
      - db_mongo_uri
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16Gb

secrets:
  # Setting the secrets to external means that the secrets are not stored in the docker-compose file and cloud formation.
  db_mongo_uri:
    name: "arn:aws:secretsmanager:ap-southeast-2:788286108805:secret:hsl-bike-app-mongo-uri-4h0gb5"
    external: true
volumes:
  mongo-data:
