version: "3.8"
name: hsl_bike_project
services:
  hsl_bike_app:
    container_name: hsl_bike_app
    build:
      context: ../
      dockerfile: ./docker/dockerfile.dev.yml
    working_dir: /home/node/app
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      NODE_ENV: development
      MONGO_URI: mongodb://app_database:27018/hsl_bike_app
    depends_on:
      - app_database

  app_database:
    container_name: app_database
    image: mongo
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
