version: "3.8"
name: hsl_bike_project
services:
  hsl_bike_app:
    container_name: hsl_bike_app
    build:
      context: ../
      dockerfile: ./docker/dockerfile.dev.yml
    working_dir: /home/node/app
    ports:
      - "8081:8080"
    environment:
      PORT: 8080
      NODE_ENV: development
      MONGO_URI: mongodb://hsl_app_database:27017/hsl_bike_app
    depends_on:
      - hsl_app_database

  hsl_app_database:
    container_name: hsl_app_database
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
