name: CI
run-name: CI process

on:
  [push]
  # pull_request:
  #   branches:
  #     - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    needs: [test, docker]
