name: CI/CD
run-name: CI/CD process

on:
  [push]
  # pull_request:
  #   branches:
  #     - main

jobs:
  # run-tests:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [19.x]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Install dependencies
  #       run: yarn install

  #     - name: Run tests
  #       env:
  #         NODE_ENV: test
  #       run: yarn test

  #     - name: Upload coverage
  #       uses: codecov/codecov-action@v3
  #       with:
  #         files: ./coverage/clover.xml

  # push-docker-image:
  #   needs: run-tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         file: ./docker/dockerfile.prod.yml
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/hsl_bike_app:latest

  deploy-to-AWS-ECS:
    # needs: push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo cloud template
        run: |
          cat ./aws/cloud_template.yml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Upload cloud formation stack to ECS
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: hsl-bike-app
          template: ./aws/cloud_template.yml
          # override the environment variables for mongo 
          parameter-overrides: >-
            DBUsername=${{ secrets.DB_USERNAME }},
            DBPassword=${{ secrets.DB_PASSWORD }},
            DBMongoUri=${{ secrets.DB_MONGO_URI }}


          