name: Codecov
run-name: Running tests and getting coverage
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codecov/codecov-action@v3
