name: Test runner
run-name: Running tests and uploading coverage to codecov
on: [pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/clover.xml
