name: docker
run-name: Upload docker image

on: 
  [push]
  # pull_request:
  #   branches:
  #     - main

jobs:
  docker:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/dockerfile.yml
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hsl_bike_app:latest
